#!/bin/bash

echo '[!] Updating...'
pacman -Sy
echo
echo '[!] Installing Dependencies...'
echo '    Python3'
yes | pacman -S python3 python-pip --needed
echo '    PHP'
yes | pacman -S php --needed
echo '    ssh'
yes | pacman -S openssh --needed 
echo '    Quo'
pip3 install quo
echo '    Requests'
pip3 install requests
echo
echo '[!] Setting Permissions...'
chmod 777 template/nearyou/php/info.txt
chmod 777 template/nearyou/php/result.txt
echo
echo '[!] Installed.'
