#!/bin/bash

echo '[!] Updating...'
apt update
echo
echo '[!] Installing Dependencies...'
echo '    Python3'
apt install python3 pip
echo '    Quo'
pip3 install quo
echo '    PHP'
apt-get -y install php
echo '    ssh'
apt-get -y install ssh
echo '    Requests'
pip3 install requests
echo
echo '[!] Setting Permissions...'
chmod 777 template/nearyou/php/info.txt
chmod 777 template/nearyou/php/result.txt
echo
echo '[!] Installed.'
